### ISSUE TITLE
[@black-flag/extensions] Expand `conflicts` functionality, rename `implies` to `requires`, and make `requires` the inverse of `conflicts`

### ISSUE THREAD

**Issue by Xunnamius** [Xunnamius/black-flag#107]
Noting this down for later!

Right now, the so-called [`implies`](https://yargs.js.org/docs/#api-reference-impliesx-y) option [doesn't actually imply anything](https://github.com/yargs/yargs/issues/2372), which makes [it](https://github.com/yargs/yargs/issues/2340) [another](https://github.com/yargs/yargs/issues/1322) [footgun](https://github.com/yargs/yargs/issues/2089) to watch out for when using yargs. Instead, the `implies` option _requires_ the specified argument(s) exist in `argv` and nothing further.

This is suboptimal for a few reasons, the foremost being the confusing use of the word "implies".

First, we can delete the `implies` option altogether by simply renaming it to `requires`. This would make `requires` the inverse of `conflicts`, which is already beautiful.

And now for the coup de grace: thanks to [BF's support for dynamic options](https://github.com/Xunnamius/black-flag?tab=readme-ov-file#built-in-support-for-dynamic-options-), it becomes trivial to expand the functionality of `conflicts` and `requires` to support declaring required or conflicting _values_ on keys, rather than just checking for the non/existence of said keys. What's more, we can use the double-parsing from dynamic options support to side-step the whole "can't use conflicts or implies with default" [footgun](https://github.com/yargs/yargs/issues/1442) since yargs has set all our defaults by the time our `conflicts`/`requires` checks are run. Easy peasy!

For example, here's a deploy command [I implemented recently](https://github.com/Xunnamius/xscripts/blob/main/src/commands/deploy.ts):

```typescript
import { type ChildConfiguration } from '@black-flag/core';
import { withBuilderExtensions, withUsageExtensions } from '@black-flag/extensions';
import { type CustomExecutionContext } from '../configure.ts';

export type CustomCliArguments = {
  target: DeployTargets;
  production?: boolean;
  preview?: boolean;
  host?: string;
  toPath?: string;
};

export const deployTargets = ['vercel', 'ssh'] as const;

export type DeployTargets = (typeof deployTargets)[number];

export default function command({ state }: CustomExecutionContext) {
  const [builder, withHandlerExtensions] =
    withBuilderExtensions<CustomCliArguments>({
      target: {
        demandOption: true,
        choices: deployTargets,
        description: 'Select deployment target and strategy'
      },
      production: {
        alias: ['prod'],
        boolean: true,
        // Both ['...', { ... }, ...] (many) and { ... } (one) syntaxes are supported for conflicts and requires
        conflicts: ['preview' /*, { target: 'ssh' }*/],
        requires: [{ target: 'vercel' }],
        description: 'Only deploy to the remote production environment'
      },
      preview: {
        boolean: true,
        conflicts: ['production' /*, { target: 'ssh' }*/],
        requires: [{ target: 'vercel' }],
        // This works in a sane way even though we're using conflicts and requires!
        default: true,
        description: 'Only deploy to the remote preview environment'
      },
      host: {
        string: true,
        /*conflicts: { target: 'vercel' },*/
        requires: { target: 'ssh' },
        description: 'The host to use when --target=ssh'
      },
      'to-path': {
        string: true,
        /*conflicts: { target: 'vercel' },*/
        requires: { target: 'ssh' },
        description: 'The deploy destination path to use when --target=ssh'
      }
    });

  return {
    builder,
    description: 'Deploy distributes to the appropriate remote',
    usage: withUsageExtensions('$1.\n\nSupports both Vercel and SSH targets!'),
    handler: withHandlerExtensions<CustomCliArguments>(async function ({
      target,
      production: productionOnly,
      preview: previewOnly,
      host,
      toPath
    }) {
      // The code here uses: state, target, productionOnly, previewOnly, host,
      // toPath, et cetera to implement the command
    })
  } satisfies ChildConfiguration<CustomCliArguments, CustomExecutionContext>;
}
```

---

Semi-related: there's a weird bug with `implies` as of yargs@17.7.2 where it barfs if you pass it an object (which its TypeScript definitions claim it supports). @black-flag/extensions typings will be amended to exclude object values.

Example:

```javascript
y.command(['$0'], 'Root description',  (y) => {
  y.options({
    x: { choices: ['a', 'b', 'c'] },
    // Intellisense says this is okay for some reason...
    y: { boolean: true, implies: { x: ... } }
  });
}, () => console.log('handler'), [], false);

y.parse(['-x', 'a']);
```
```text
YError: Invalid second argument. Expected number or string or array but received object.
    at c (/repos/xscripts/node_modules/yargs/build/index.cjs:1:2269)
    at /repos/xscripts/node_modules/yargs/build/index.cjs:1:2121
    at Array.forEach (<anonymous>)
    at h (/repos/xscripts/node_modules/yargs/build/index.cjs:1:2018)
    at te.implies (/repos/xscripts/node_modules/yargs/build/index.cjs:1:37541)
    at te.option (/repos/xscripts/node_modules/yargs/build/index.cjs:1:39153)
    at te.options (/repos/xscripts/node_modules/yargs/build/index.cjs:1:40171)
    at /repos/xscripts/node_modules/yargs/build/index.cjs:1:38298
    at Array.forEach (<anonymous>)
    at te.option (/repos/xscripts/node_modules/yargs/build/index.cjs:1:38280)
Uncaught TypeError: e.match is not a function
    at a (/repos/xscripts/node_modules/yargs/build/index.cjs:1:55181)
    at /repos/xscripts/node_modules/yargs/build/index.cjs:1:55751
    at Array.forEach (<anonymous>)
    at /repos/xscripts/node_modules/yargs/build/index.cjs:1:55709
    at Array.forEach (<anonymous>)
    at r.implications (/repos/xscripts/node_modules/yargs/build/index.cjs:1:55675)
    at /repos/xscripts/node_modules/yargs/build/index.cjs:1:60269
```

Honestly, I'm not sure what vanilla yargs's object form of `implies` is supposed to mean.

**Comment by Xunnamius** [comment]
See https://github.com/Xunnamius/black-flag-extensions
